### ISSUE TITLE
feature request: add conditional creation for ServiceMonitors on blockscout-stack

### ISSUE THREAD

**Issue by refl3ction** [blockscout/helm-charts#1]
### Description

Currently, the `blockscout-stack` Chart always tries to create the ServiceMonitors if `blockscout.enabled` is true. If Prometheus CRDs are not installed in the cluster, this will break the installation.

> Error: unable to build kubernetes objects from release manifest: resource mapping not found for name: "blockscout-stack-blockscout-svm" namespace: "" from "": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"

**Comment by nzenchik** [comment]
We've implemented this feature, serviceMonitors can be disabled with this setting - https://github.com/blockscout/helm-charts/blob/8c9635e9a3ad8792ab363abe6db3170bc758d31b/charts/blockscout-stack/values.yaml#L30
