### ISSUE TITLE
Wrong value for tls.secretName in frontend-ingress resource

### ISSUE THREAD

**Issue by ivel13** [blockscout/helm-charts#11]
Chart: **blockscout-stack**
In the [frontend-ingress.yaml](https://github.com/blockscout/helm-charts/blob/main/charts/blockscout-stack/templates/frontend-ingress.yaml#L34C43-L34C43) file `spec.tls.secretName` is pointing to the wrong value:
`secretName: {{ .Values.blockscout.ingress.tls.secretName | default (printf "%s-frontend-tls" $fullName) }}`
But it should be:
`secretName: {{ .Values.frontend.ingress.tls.secretName | default (printf "%s-frontend-tls" $fullName) }}`

**Comment by nzenchik** [comment]
Fixed in [1.3.4](https://github.com/blockscout/helm-charts/releases/tag/blockscout-stack-1.3.4) version
