### ISSUE TITLE
stats config map missing volume mount

### ISSUE THREAD

**Issue by frisitano** [blockscout/helm-charts#15]
It appears that that volume mount for the stats config map is missing. It may have accidentally been added to `frontend-deployment.yaml` instead of `stats-deployment.yaml`?

https://github.com/blockscout/helm-charts/blob/8c9107a1b8c244b87e606e86f07075e658d34fa5/charts/blockscout-stack/templates/frontend-deployment.yaml#L86-L94

**Comment by nzenchik** [comment]
Fixed by this https://github.com/blockscout/helm-charts/commit/26f5897fe0c79af434fd7c0fb4ff37f27a9b5c36
