### ISSUE TITLE
Blockscout stats-cm name not unique

### ISSUE THREAD

**Issue by frisitano** [blockscout/helm-charts#17]
The configmap used for the stats service is not unique and as such when we deploy multiple instances of blockscout stats chart in the same namespace we experience conflicts.  We should make the naming unique - i.e:

```
{{- $fullName := include "blockscout-stack.fullname" . -}}
...
metadata:
  name: {{ $fullName }}-stats-cm
```

We will also need to update the references to this config map.

**Comment by nzenchik** [comment]
It was fixed in [this release](https://github.com/blockscout/helm-charts/releases/tag/blockscout-stack-1.4.3)
