### ISSUE TITLE
Frontend Container in error after deploy

### ISSUE THREAD

**Issue by MaxTeiger** [blockscout/helm-charts#4]
Hello, 

When I am trying to deploy a blockscout instance in my Kubernetes Cluster using blockscout-stack, my frontend containers are in error with the following error message : 

```bash
⏳ Validating environment variables schema...
_e [ZodValidationError]:
  Required at "NEXT_PUBLIC_API_HOST"
    at ve (/app/envs-validator.js:1:56363)
    at /app/envs-validator.js:1:1182
    at Generator.next (<anonymous>)
    at /app/envs-validator.js:1:355
    at new Promise (<anonymous>)
    at a (/app/envs-validator.js:1:100)
    at /app/envs-validator.js:1:987
    at /app/envs-validator.js:1:1329
    at Generator.next (<anonymous>)
    at /app/envs-validator.js:1:355 {
  details: [
    {
      code: 'invalid_type',

      expected: 'string',
      received: 'undefined',
      path: [Array],
      message: 'Required'
    }
  ]
}
🚨 Environment variables set is invalid.
🛑 ENV integrity check failed.
```

But it seems I filled the `values.yaml` file correctly and I see no option to set this variable in the values file. So I had to add it manually. 

Maybe it would be better if it was an option in `config` as some other environment variables for `NEXT` ? 😄 

Thank you !

**Comment by nzenchik** [comment]
Hi, NEXT_PUBLIC_API_HOST var is equals to blockscout.ingress.hostname. Also you to enable ingress for blockscout. NEXT_PUBLIC_APP_HOST equals to frontend.ingress.hostname.

**Comment by MaxTeiger** [comment]
Ok thank you, I'll try it 👍🏼

**Comment by MaxTeiger** [comment]
Thank you it seems that it worked as expected. But it seems my frontend is still unable to fetch transactions / blocks... Do you have an idea on why this can happen ? 

Otherwise my "API" seems to fetch blocks normally.
API: https://blockscout-poa.api.staging.arianee.com/
Frontend: https://blockscout-poa.staging.arianee.com/

**Comment by nzenchik** [comment]
It seems that you instance is slow, try to check resources for backend and Postgresql - as I see on old UI https://blockscout-poa.api.staging.arianee.com/ transactions fetches from time to time. The same is for new UI on https://blockscout-poa.staging.arianee.com/
