### ISSUE TITLE
Add sample environment variables to blockscout-stack

### ISSUE THREAD

**Issue by refl3ction** [blockscout/helm-charts#5]
### Description

It would be good if the required env vars for blockscout API and frontend were filled in the Helm Chart. They could be at least commented, so it would be easier for operators to figure out the best way to run that on k8s.

**Comment by air3ijai** [comment]
There a lot of variables, especially for frontend and sometimes they may changes. Just to now have double work or have outdated information, it make sense to provide the links the the current documentation, which we have already

https://github.com/blockscout/helm-charts/blob/bbf43e41ce06c4b8cce0ce2711bfdef868bd9a4b/charts/blockscout-stack/values.yaml#L58-L62

https://github.com/blockscout/helm-charts/blob/bbf43e41ce06c4b8cce0ce2711bfdef868bd9a4b/charts/blockscout-stack/values.yaml#L200-L204

**Comment by nzenchik** [comment]
As mentioned above there are a lot of env vars for both frontend and backend and it does not make sense to add all of them here. Also the list of variables is dynamic and we think that it make sense to add links to docs instead of maintaining list of variables in both places - helm chart and docs.
